[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./entrypoint.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 20
healthcheckTimeout = 300
healthcheckPath = "/actuator/health"

[env]
PORT = "8080" 